### ISSUE TITLE
Dot in keyname clashes with drilldown token

### ISSUE THREAD

**Issue by daniellowtw** [simeji/jid#54] opened 2017-01-06 14:47 UTC
The drilldown token `.` can appear in the key name of the json object and will break drilling down

```
> echo '{ "a.a": 123 }' | jid

[Filter]> .
{    
  "a.a": 123
}

[Filter]> .a.a
 null

[Filter]> ."a.a"    
 null
```

The first prompt suggested the autocomplete `.a.a` which doesn't work.

**Comment by daveloyall** [comment] 2017-02-21 18:04
Duplicate of #32.

**Comment by fiatjaf** [comment] 2017-03-02 23:34
Shameless self-promotion: that feature is supported in https://github.com/fiatjaf/jiq, which is a fork of the amazing jid, but using the jq parser, such that complicated keys like "a.a" are supported like `.["a.a"]`.

**Comment by simeji** [comment] 2019-04-01 16:44
@daniellowtw

I've fixed this issue in https://github.com/simeji/jid/releases/tag/v0.7.6

**Comment by simeji** [comment] 2019-04-02 16:39
I

**Comment by simeji** [comment] 2019-04-02 16:40
If you have any questions, plz open this issue again.

**Comment by simeji** [comment] 2019-04-02 16:40
If you have any questions, plz open this issue again.

**Closed by simeji** 2019-04-02 16:40 UTC
